// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bgadrttmqhuaimhzfzsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnYWRydHRtcWh1YWltaHpmenNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDQzNjgsImV4cCI6MjA3MjM4MDM2OH0.Qy9pVaLpupQwnv5QPQi0o-u2ikQ4EBo9sxur5hbKZMI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});